CREATE TABLE conta_bancaria (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    banco VARCHAR(50) NOT NULL,
    tipo VARCHAR(30) NOT NULL, -- CONTA_CORRENTE, CARTAO_CREDITO, INVESTIMENTO
    agencia VARCHAR(20),
    numero_conta VARCHAR(30),
    final_cartao VARCHAR(4),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
