CREATE TABLE parametro (
    id BIGSERIAL PRIMARY KEY,
    chave VARCHAR(100) NOT NULL UNIQUE,
    valor TEXT,
    descricao VARCHAR(255),
    tipo VARCHAR(30) NOT NULL DEFAULT 'STRING', -- STRING, NUMBER, BOOLEAN, PASSWORD
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
