-- SCRIPT DE LIMPEZA E ZERAGEM COMPLETA DAS TABELAS DE TRANSAÇÕES
TRUNCATE TABLE operacao RESTART IDENTITY CASCADE;
TRUNCATE TABLE dividendo RESTART IDENTITY CASCADE;
TRUNCATE TABLE fii RESTART IDENTITY CASCADE;
TRUNCATE TABLE ativo RESTART IDENTITY CASCADE;
TRUNCATE TABLE lancamento RESTART IDENTITY CASCADE;
